[package]
name = "oklab"
version = "0.1.0"
edition = "2021"
license = "MIT or Apache-2.0"

[dependencies]
serde = { version = "1.0.193", features = ["derive"], optional = true }

[dev-dependencies]
rand = "0.8.5"

[features]
serde = ["dep:serde"]
