[package]
name = "attractor-egui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.23.0"
egui-wgpu = "0.23.0"
egui-winit = "0.23.0"
render = { path = "../render" }
attractors = { path = "../attractors" }
oklab = { path = "../oklab" }
rand = "0.8.5"
egui_extras = "0.23.0"
wallpaper = "3.2.0"
image = "0.24.7"
